schema_version = "1.0.0"

id = "wiggle_bones"
name = "Wiggle Bones"
version = "1.1.2"
blender_version_min = "4.5.0"

tagline = "Refactor of Wiggle 2, fully fixed for Blender 5.0"
maintainer = "Hans Xwh"
type = "add-on"
tags = ["Physics"]
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 Hans_Xwh"]

website = "https://github.com/Hans-xwh/wiggle-bones"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "*.old"
]
