"""Historical hair cleanup refuses external Blender ID references atomically.

The fixture is generated by the frozen 0.40.2 release in a separate process.
Run with --background --factory-startup --disable-autoexec --python-exit-code 1.
"""

import json
from pathlib import Path
import subprocess
import sys
import tempfile
import zipfile

import bpy

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "addons"))
sys.path.insert(0, str(ROOT / "tests"))
from character_designer import hair_bones_binding as binding
from character_designer import hair_bones_rig as rig
from character_designer import hair_bones_variants as variants
from test_hair_bones_variants_blender import source_state


def data_inventory():
    return {name: tuple(sorted((item.name, item.as_pointer()) for item in getattr(bpy.data, name)))
            for name in ("objects", "collections", "meshes", "armatures", "materials", "node_groups", "actions")}


def add_driver(owner, data_path, target, *, index=None):
    curve = owner.driver_add(data_path) if index is None else owner.driver_add(data_path, index)
    variable = curve.driver.variables.new()
    variable.name = "hair_value"
    variable.type = "SINGLE_PROP"
    variable.targets[0].id_type = "COLLECTION" if isinstance(target, bpy.types.Collection) else "OBJECT"
    variable.targets[0].id = target
    variable.targets[0].data_path = "hide_render" if isinstance(target, bpy.types.Collection) else "location.x"
    curve.driver.expression = "hair_value"
    return curve


def add_geometry_nodes_reference(source, mesh, armature, collection):
    data = bpy.data.meshes.new("External Geometry Nodes Mesh")
    obj = bpy.data.objects.new("External Geometry Nodes", data)
    bpy.context.scene.collection.objects.link(obj)
    tree = bpy.data.node_groups.new("External Hair Input", "GeometryNodeTree")
    socket = tree.interface.new_socket(name="Hair Object", in_out="INPUT", socket_type="NodeSocketObject")
    modifier = obj.modifiers.new("Geometry Nodes", "NODES")
    modifier.node_group = tree
    if hasattr(modifier, "properties"):
        value = getattr(modifier.properties.inputs, socket.identifier)
        value.value = mesh
        return lambda: setattr(value, "value", None)
    modifier[socket.identifier] = mesh
    return lambda: modifier.__setitem__(socket.identifier, None)


def add_collection_instance(source, mesh, armature, collection):
    obj = bpy.data.objects.new("External Hair Collection Instance", None)
    bpy.context.scene.collection.objects.link(obj)
    obj.instance_type = "COLLECTION"
    obj.instance_collection = collection
    return lambda: setattr(obj, "instance_collection", None)


def add_material_driver(source, mesh, armature, collection):
    material = bpy.data.materials.new("External Material Driver")
    add_driver(material, "diffuse_color", mesh, index=0)
    return lambda: material.driver_remove("diffuse_color", 0)


def add_node_tree_driver(source, mesh, armature, collection):
    material = bpy.data.materials.new("External Embedded Node Tree Driver")
    material.use_nodes = True
    node = material.node_tree.nodes.new("ShaderNodeValue")
    socket = node.outputs[0]
    add_driver(socket, "default_value", armature)
    return lambda: socket.driver_remove("default_value")


def add_scene_driver_to_collection(source, mesh, armature, collection):
    scene = bpy.context.scene
    scene["external_hair_value"] = 0.0
    add_driver(scene, '["external_hair_value"]', collection)
    return lambda: scene.driver_remove('["external_hair_value"]')


def add_scene_driver_to_unlinked_rig(source, mesh, armature, collection):
    for parent in tuple(armature.users_collection):
        parent.objects.unlink(armature)
    scene = bpy.context.scene
    scene["external_unlinked_hair"] = 0.0
    add_driver(scene, '["external_unlinked_hair"]', armature)
    return lambda: scene.driver_remove('["external_unlinked_hair"]')


def add_scene_custom_reference(source, mesh, armature, collection):
    scene = bpy.context.scene
    scene["external_hair_nested"] = {"target": collection}
    return lambda: scene.__delitem__("external_hair_nested")


def add_collection_parent_extra_reference(source, mesh, armature, collection):
    parent = bpy.data.collections.new("Artist Parent Collection")
    bpy.context.scene.collection.children.link(parent)
    parent.children.link(collection)
    bpy.context.scene.collection.children.unlink(collection)
    parent["external_hair_nested"] = {"target": collection}
    return lambda: parent.__delitem__("external_hair_nested")


def run_dependency_case(directory, expected, add_reference):
    bpy.ops.wm.open_mainfile(filepath=str(directory / "legacy.blend"))
    source = bpy.data.objects[expected["source"]]
    collection = bpy.data.collections[expected["version"]]
    mesh, armature = collection[variants.MESH_KEY], collection[variants.ARMATURE_KEY]
    remove_reference = add_reference(source, mesh, armature, collection)
    bpy.context.view_layer.update()
    before, original = data_inventory(), source_state(source)
    try:
        binding.remove_generated_copies(bpy.context, source)
    except rig.HairBonesRigError as exc:
        assert any(text in str(exc).lower() for text in ("uses", "depends", "dependency")), str(exc)
    else:
        raise AssertionError(f"{add_reference.__name__}: deleting a referenced copy must be refused")
    assert data_inventory() == before, "Refused cleanup deleted or created datablocks"
    assert source_state(source) == original
    remove_reference()
    bpy.context.view_layer.update()
    names = mesh.name, armature.name, collection.name
    result = binding.remove_generated_copies(bpy.context, source)
    assert result["removed_meshes"] == result["removed_rigs"] == 1
    assert bpy.data.objects.get(names[0]) is None and bpy.data.objects.get(names[1]) is None
    assert bpy.data.collections.get(names[2]) is None
    assert bpy.data.objects.get(source.name) is source and source_state(source) == original
    if add_reference is add_collection_parent_extra_reference:
        assert bpy.data.collections.get("Artist Parent Collection") is not None
    print("PASS", add_reference.__name__)


if __name__ == "__main__":
    with tempfile.TemporaryDirectory(prefix="hair-cleanup-dependencies-") as temporary:
        directory = Path(temporary)
        old_addons = directory / "old-addons"
        with zipfile.ZipFile(ROOT / "dist" / "character_designer-0.40.2.zip") as archive:
            assert all(Path(name).parts[0] == "character_designer" and ".." not in Path(name).parts for name in archive.namelist())
            archive.extractall(old_addons)
        process = subprocess.run([bpy.app.binary_path, "--background", "--factory-startup", "--disable-autoexec",
                                  "--python-exit-code", "1", "--python", str(ROOT / "tests" / "test_hair_bones_legacy_compat_blender.py"),
                                  "--", "legacy-create", str(old_addons), str(directory)],
                                 capture_output=True, text=True, timeout=120)
        assert process.returncode == 0, (process.stdout, process.stderr)
        expected = json.loads((directory / "expected.json").read_text(encoding="utf-8"))
        for add_reference in (add_geometry_nodes_reference, add_collection_instance,
                              add_material_driver, add_node_tree_driver, add_scene_driver_to_collection,
                              add_scene_driver_to_unlinked_rig, add_scene_custom_reference,
                              add_collection_parent_extra_reference):
            run_dependency_case(directory, expected, add_reference)
    print("HAIR_CLEANUP_DEPENDENCIES_OK 8")
