<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>9.0</LangVersion>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <NoWarn>1701;1702;0649</NoWarn>
    <DefineConstants>UNITY_EDITOR</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="D:/MyRepository/Blender-addons-by-Randy/addons/character_designer/unity_runtime/Runtime/*.cs" />
    <Compile Include="D:/MyRepository/Blender-addons-by-Randy/addons/character_designer/unity_runtime/Editor/*.cs" />
    <Reference Include="C:/Program Files/Unity/Hub/Editor/6000.5.9f1/Editor/Data/Managed/UnityEngine/*.dll" />
    <Reference Include="C:/Program Files/Unity/Hub/Editor/6000.5.9f1/Editor/Data/Managed/UnityEditor/*.dll" />
    <Reference Include="D:/Unity Projects/RandomRealm2/Library/ScriptAssemblies/Unity.Collections.dll" />
  </ItemGroup>
</Project>
